<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    //第一种：
    // new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve('aaa')
    //   },1000)
    // }).then((data) => {
    //   console.log(data)
    //   console.log(data)

    //   return new Promise((resolve, reject) => {
    //     resolve(data+'111')
    //   })
    // }).then((data) => {
    //   console.log(data)

    //   return new Promise((resolve) => {
    //     resolve(data+'222')
    //   })
    // }).then(res => {
    //   console.log(res)
    // })
    //第二种：new Promise(resolve => resolve(结果))简写
    // new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve('aaa')
    //   },1000)
    // }).then((data) => {
    //   console.log(data)
    //   console.log(data)
    //   //对结果进行第一次处理
    //   return Promise.resolve(data+'111')
    // }).then((data) => {
    //   console.log(data)
    //   //对结果进行第二次处理
    //   return Promise.resolve(data+'222')
    // }).then(res => {
    //   console.log(res)
    // })
    //第三种：更简洁 省略掉Promise.resolve
    // new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve('aaa')
    //   },1000)
    // }).then((data) => {
    //   console.log(data)
    //   console.log(data)
    //   //对结果进行第一次处理
    //   return data+'111'
    // }).then((data) => {
    //   console.log(data)
    //   //对结果进行第二次处理
    //   return data+'222'
    // }).then(res => {
    //   console.log(res)
    // })
    //第四种：万一被拒绝
     new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('aaa')
      },1000)
    }).then((data) => {
      console.log(data)
      console.log(data)
      //对结果进行第一次处理
      // return Promise.reject('error')
      //也可以抛出异常
      throw 'error'
    }).then((data) => {
      console.log(data)
      //对结果进行第二次处理
      return Promise.resolve(data+'222')
    }).then(res => {
      console.log(res)
    }).catch(err => {
      console.log(err)
    })
  </script>
</body>
</html>